# Generated by Django 6.0.4 on 2026-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Premium Builders', max_length=150)),
                ('hero_title', models.CharField(default='Building Excellence, Engineering the Future.', max_length=200)),
                ('hero_subtitle', models.CharField(default='Premium Commercial & Residential Construction Delivered with Precision', max_length=300)),
                ('about_snippet', models.TextField(default='Reliability, precision, and excellence in every project. Building the future sustainably and professionally.')),
                ('about_page_text', models.TextField(default='Since our founding, we have been committed to delivering projects of the highest quality...')),
                ('contact_phone', models.CharField(default='+1 (234) 567-890', max_length=50)),
                ('contact_email', models.EmailField(default='info@premiumbuilders.com', max_length=254)),
                ('contact_address', models.CharField(default='123 Construction Blvd, City', max_length=300)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
    ]
