# Generated by Django 6.0.4 on 2026-04-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon image', null=True, upload_to='services/icons/'),
        ),
    ]
