# Generated by Django 6.0.4 on 2026-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_icon_service_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_primary',
            field=models.CharField(default='Request a Free Quote', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_secondary',
            field=models.CharField(default='View Our Work', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_label',
            field=models.CharField(default='Experience', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_1_value',
            field=models.CharField(default='20+ Years', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_label',
            field=models.CharField(default='Generated', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_2_value',
            field=models.CharField(default='ISO 9001', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_label',
            field=models.CharField(default='Projects Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_3_value',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_label',
            field=models.CharField(default='Safety Record', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_4_value',
            field=models.CharField(default='100%', max_length=50),
        ),
    ]
