# Generated by Django 6.0.4 on 2026-04-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_hero_cta_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Our Company', max_length=200)),
                ('hero_subtitle', models.CharField(default='Mastering the Art of Construction Since 2005', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('content_title', models.CharField(default='Our Heritage', max_length=200)),
                ('content_intro', models.TextField(default='We are more than just builders; we are partners in bringing your vision to life.')),
                ('content_body', models.TextField(default='Since our founding...\n\nWe employ cutting-edge technology...')),
            ],
        ),
    ]
